[package]
name = "radeco"
version = "0.1.0"
authors = [
	"pancake <pancake@nopcode.org>"
]

[dependencies]
r2pipe = "*"
docopt = "*"
rustc-serialize = "*"

[dependencies.radeco-lib]
git = "https://github.com/radare/radeco-lib"
